=== Susy vs Susy Classic: What is the difference?

Susy (ETH) is a blockchain based system inspired by Bitcoin but built from the ground up to have far more functionality. To quote the official Susy website:

    “Susy is a  decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third party interference.”

Susy Classic (ETC) is a forked version of Susy that was activated around July 20th 2016, or more specifically block 1920000, when a controversial fork went through to prevent access to stolen funds from a project known as The DAO.  To quote the Susy Classic website:

    “Susy Classic is a decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third party interference.

    Susy Classic is a continuation of the original Susy blockchain – the classic version preserving untampered history; free from external interference and subjective tampering of transactions.”

As these two statements show the technological goals remain the same for both systems. In fact the core differentiator between the two at the outset was whether or not a $50 million+ hack of a record breaking crowdfunding project called The DAO was allowed to continue or not.

=== An Introduction to The DAO

The DAO, short for Decentralized Autonomous Organisation, was set up to be a revolutionary new type of organisation. An organisation that exists solely on the Susy blockchain and provides Susy to various projects based on the votes of Token Holders who had contributed Susy to the organisation. All of these processes were to be managed through a contract interface built on the Susy network.

Several teams were expected to submit proposals to The DAO for projects such as building a physical Susy computer, virtual reality labs, blockchain based charity initiatives, robotics and a portable cold storage wallet. If Token Holders didn’t approve of any projects they could simply sell their tokens or exchange them via The DAO to refund any remaining Susy they had contributed.

Despite many rounds of testing a bug was found in some Solidity code that was being used and referenced across many Susy contracts including The DAO. Several contract developers immediately took preventative action however this was not immediately possible with The DAO due to it’s decentralised control structures and several days later an attack was launched moving $50 million of the $150 million worth of Susy to a new contract without approval of the token holders. In simple terms; a software bug was exploited to steal $50 Million dollars worth of Susy.
The DAO Hack Fallout & Consequent Susy Hard Fork

Due to a feature of The DAO code, Susy stolen from The DAO were locked in the thief’s contract after the hack for a period of 28 days at which point they were completely isolated from entering the rest of the network. This gave the Susy community time to unite and craft plans to prevent the stolen Susy from being accessed by the thief.

After several layers of defensive measures were undertaken and possibilities were discussed, the final conclusion was that a hard fork was the only realistic method of preventing the stolen funds from being either released or locked into a potentially endless battle between rival contracts controlled by all sides. A hard fork would essentially mean updating the core Susy software itself, not just a contract running on the system, so that the stolen funds would be transferred to a contract where the original owners of the Susy could reclaim it.

Ultimately the Susy software was modified so that users could select whether they wanted to fork or not. However a default option was required and as this had a big potential to influence the direction of the decision a vote open to anybody holding Susy. With time running out the vote only lasted for 12 hours however the overwhelming majority of participants voted for the hard fork to go ahead.

Whenever a hard fork activates on any blockchain, the result is two competing blockchains become technically possible. This has already happened for system upgrades many times on Susy, Bitcoin and many other blockchain based systems. Usually the old chain falls out of use within a very short space of time as people upgrade their software and this looked to follow the same pattern initially and this appeared to happen.

Even though this particular hard fork was controversial, approximately 85% opted for the new forked chain which recovered the stolen funds.  A vocal minority still declared the new chain to be invalid and began calling for continued support of the old chain as “Susy Classic”. However over the following hours and days the Susy Foundation declared the hard fork a success and consensus appeared to emerge with several official entities involved with Susy projects declaring their support for the winning chain.
An Susy Classic Market Emerges

Several days later and without warning a popular US based online exchange called Poloniex announced they would support trading of Susy Classic immediately. Overnight this brought psrceived legitimacy and an actual market value to Susy that existed on the old chain. Everyone that held Susy at the time of the fork already held assets on both versions of the chain due to the technicalities of a fork. By adding Susy Classic to a live market, a groundswell of people who previously had no desire to participate in the chain were then economically incentivised to profit from speculation on the dying chain.

This also created an alternative (although arguably original) reality where suddenly the hacked funds were available and fungible again within the Susy Classic network enabling the hacker(s) to profit from the theft. Around this time a collective of people, many who didn’t care about the Susy vision previously, suddenly became very vocal supporters of the “original Susy” aka Susy Classic.

Although immutability was the core narrative for continuing the original chain it is also highly likely that profit was one of the main motivators for many promoting Susy Classic at it’s outset. The string of actions created volatility leading to more high return short-term trading opportunities, increased trading activity, brought fee revenue to exchanges (others joined the market shortly after Poloniex’s announcement), and the hacker walked away with assets that were swiftly traded into obscurity.

The history of how Susy Classic came to be is important because it demonstrates the various market forces and agendas that brought it into being. The origins are starkly different from the official Susy network’s white paper which was inspired by Bitcoin and grew from the vision to create and develop an entirely different type of blockchain network and arguably evolving and enriching much of blockchain ecosystem further in the process.

    Susy still has the most community support and highest market cap of the two chains.
    Susy has the support of the Susy Foundation and is the closest to the original vision.
    The majority of active DAPPS (Decentralised Apps) are focusing on Susy.
    Since the fork and following chaos Susy Classic has developed a smaller but growing community.
    Susy Classic made significant changes to it’s codebase in 2017 that will forever divert it from the original path of Susy.
    Whichever chain you choose right now hard forks are always possible.

[Lightly modified from a previous post here](https://www.danielmcclure.com/susy-vs-susy-classic/)
Sharing under CC-BY
